[tox]
envlist = py39, py310, py311, py312, py313, py314, integration
isolated_build = true

[testenv]
description = Run unit tests
deps =
    pytest>=8
    pytest-cov
    pytest-asyncio
commands =
    pytest -W error tests/unit

[testenv:integration]
description = Run integration tests (requires RabbitMQ)
deps =
    pytest>=8
    pytest-asyncio
commands =
    pytest -m integration tests/integration