# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wire.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nwire.proto\x12\x07is.wire\x1a\x19google/protobuf/any.proto\"8\n\x06Status\x12!\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x13.is.wire.StatusCode\x12\x0b\n\x03why\x18\x02 \x01(\t\"\xeb\x01\n\nWireFormat\x12\r\n\x03raw\x18\x01 \x01(\x0cH\x00\x12\'\n\x07message\x18\x02 \x01(\x0b\x32\x14.google.protobuf.AnyH\x00\x12\x12\n\ncreated_at\x18\x03 \x01(\x04\x12*\n\x0c\x63ontent_type\x18\x04 \x01(\x0e\x32\x14.is.wire.ContentType\x12\x1f\n\x06status\x18\x05 \x01(\x0b\x32\x0f.is.wire.Status\x12\x16\n\x0e\x63orrelation_id\x18\x06 \x01(\x04\x12\x10\n\x08reply_to\x18\x07 \x01(\t\x12\x12\n\nexpires_in\x18\x08 \x01(\rB\x06\n\x04\x62ody*\xfe\x01\n\nStatusCode\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x06\n\x02OK\x10\x01\x12\r\n\tCANCELLED\x10\x02\x12\x14\n\x10INVALID_ARGUMENT\x10\x03\x12\x15\n\x11\x44\x45\x41\x44LINE_EXCEEDED\x10\x04\x12\r\n\tNOT_FOUND\x10\x05\x12\x12\n\x0e\x41LREADY_EXISTS\x10\x06\x12\x15\n\x11PERMISSION_DENIED\x10\x07\x12\x13\n\x0fUNAUTHENTICATED\x10\x08\x12\x17\n\x13\x46\x41ILED_PRECONDITION\x10\t\x12\x10\n\x0cOUT_OF_RANGE\x10\n\x12\x11\n\rUNIMPLEMENTED\x10\x0b\x12\x12\n\x0eINTERNAL_ERROR\x10\x0c*>\n\x0b\x43ontentType\x12\x08\n\x04NONE\x10\x00\x12\x0c\n\x08PROTOBUF\x10\x01\x12\x08\n\x04JSON\x10\x02\x12\r\n\tPROTOTEXT\x10\x03\x42\x0f\n\x0b\x63om.is.wireP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wire_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\013com.is.wireP\001'
  _STATUSCODE._serialized_start=347
  _STATUSCODE._serialized_end=601
  _CONTENTTYPE._serialized_start=603
  _CONTENTTYPE._serialized_end=665
  _STATUS._serialized_start=50
  _STATUS._serialized_end=106
  _WIREFORMAT._serialized_start=109
  _WIREFORMAT._serialized_end=344
# @@protoc_insertion_point(module_scope)
